#!/usr/bin/env python
# -*- coding: utf-8 -*-

# WaxChooser -- A utility for finding the appropriate ski wax for the given conditions
#
# Copyright (C) 2010 Benjamin Deering <waxChooserMaintainer@swissmail.org>
# http://jeepingben.homelinux.net/wax/
#
# This file is part of WaxChooser.
#
# WaxChooser is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# WaxChooser is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from waxChooser import waxChooser 

if __name__ == '__main__':
    waxChooser.waxGUI()
